# ================================= API ================================
FROM python:3.8-alpine AS cmdb-api

LABEL description="Python3.8,cmdb"

COPY cmdb-api /data/apps/cmdb

WORKDIR /data/apps/cmdb

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add --no-cache tzdata gcc musl-dev libffi-dev openldap-dev python3-dev jpeg-dev zlib-dev build-base

ENV TZ=Asia/Shanghai

RUN pip install  --no-cache-dir -r requirements.txt \
    && if [ -f settings.example.py ]; then \
        cp settings.example.py settings.py && \
        sed -i "s#{user}:{password}@127.0.0.1:3306/{db}#cmdb:123456@cmdb-db:3306/cmdb#g" settings.py && \
        sed -i "s#redis://127.0.0.1#redis://cmdb-cache#g" settings.py && \
        sed -i "s#CACHE_REDIS_HOST = '127.0.0.1'#CACHE_REDIS_HOST = 'cmdb-cache'#g" settings.py && \
        echo "Settings configured successfully"; \
    else \
        echo "settings.example.py not found!"; \
        ls -la; \
    fi

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

CMD ["sh", "-c", "/wait && flask run --host=0.0.0.0 --port=5000"]